### ISSUE TITLE
How do I improve the speed from this?

### ISSUE THREAD

**Issue by wildorwilliamgit** [jschr/electron-react-redux-boilerplate#107]
Hi
Thanks for your efforts.
I think it is great. thanks again.
I used this git, and my project works fine.
But the problem is that the electron app which started from this, is very slow on pc.
The pc's cpu is core 2 duo.
How can I improve the speed? 
Any help will be appreciated.
Thanks a lot.

**Comment by pronebird** [comment]
Please ask electron related questions on Electron community or Stackoverflow.

https://www.electronjs.org/
https://stackoverflow.com/
