### ISSUE TITLE
libnss3.so - watch-html when running

### ISSUE THREAD

**Issue by Lemorz56** [jschr/electron-react-redux-boilerplate#109]
Getting this error when running npm run develop and then it hangs

Windows 10, npm install works without errors.

`[14:49:01] Starting 'watch-html'...
/mnt/d/CODE/electron-react-redux-boilerplate/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

**Comment by pronebird** [comment]
Does it happen on Windows only? Electron should not require `libnss3.so` on Windows.

**Comment by pronebird** [comment]
I guess it's more related to Electron. I honestly don't have an answer. Quick googling reveals that there are some efforts to make it work under WSL, i.e: https://gist.github.com/caseywatts/9700b402b6b51d1d6af9f0b206739770

**Comment by Lemorz56** [comment]
> I guess it's more related to Electron. I honestly don't have an answer. Quick googling reveals that there are some efforts to make it work under WSL, i.e: https://gist.github.com/caseywatts/9700b402b6b51d1d6af9f0b206739770

Thanks a lot! ☺️
