### ISSUE TITLE
Error on packing script

### ISSUE THREAD

**Issue by drseven** [jschr/electron-react-redux-boilerplate#11]
Hi, I cloned this repo and when I try to pack it, I get this error:

> Error: ENOENT: no such file or directory, open '[..]\electron-react-redux-boilerplate\cache\package.json'

Node Version: v6.9.3
Windows 7

thanks for your support :)

**Comment by pronebird** [comment]
Unfortunately, packaging is currently broken.

**Comment by pronebird** [comment]
#16 fixes this
