### ISSUE TITLE
Login doesn't work in packed app

### ISSUE THREAD

**Issue by PhilJ** [jschr/electron-react-redux-boilerplate#2]
I cloned the repo (OS X 10.10.5, node v3.2.0) and try to run it, but I have troubles with the packed app.

When starting the app with `npm run serve` the client is functional and I receive a greeting after clicking on the "Log in" Button. 

When I build with `npm run pack` I receive a success build, which I can start and which shows the login form. However nothing happens when I press the "Log in" button.

Do you have any idea what could be wrong with the build?

**Comment by jschr** [comment]
@PhilJ Can you confirm if running the result of the pack from outside of the project folder works? 

I believe the issue has something to do with node_modules being bundled with `pack` as well as also being inside the project which causes React to be loaded in twice.

**Comment by PhilJ** [comment]
Yes, I can confirm :+1: 

The client works as expected as soon as i copy it to another directory. 

Thanks for the quick support and sharing your nice and slim boilerplate!

**Comment by jschr** [comment]
Your welcome! I will update the readme with this info.
