### ISSUE TITLE
Rebuilding native modules

### ISSUE THREAD

**Issue by jschr** [jschr/electron-react-redux-boilerplate#20]
It seems like the only thing we might be missing when compared to [electron-forge](https://github.com/electron-userland/electron-forge) is native module rebuilding. 

Electron forge uses [electron-rebuild](https://github.com/electron/electron-rebuild) for this so this may be something to include with the boilerplate.

Keeping as discussion for now because I haven't needed to use a native module yet. 

@pronebird in your project, are you handling native modules somehow?

**Comment by pronebird** [comment]
I don't know much about native modules. However documentation for electron-builder mentions them:

>If you have native addons of your own that are part of the application (not as a dependency), add "nodeGypRebuild": true to the build section of your development package.json.

**Comment by jschr** [comment]
Ah, interesting. So looks like we already support them then. 

From electron-rebuild

> This allows you to use native Node.js modules in Electron apps without your system version of Node.js matching exactly (which is often not the case, and sometimes not even possible)

So it seems like maybe we can leave it out for now in the interest of keeping dependencies minimal. 

If it becomes an issue we can add it later pretty easily.

**Comment by pronebird** [comment]
Just had a chance to build and run native extension in my electron app. As expected electron-builder does everything properly. `npm i` rebuilds native deps. 👍
