### ISSUE TITLE
some error with npm install

### ISSUE THREAD

**Issue by Tanjh1996** [jschr/electron-react-redux-boilerplate#27]
i use npm install but has error.How can i deal with it?
![error](https://cloud.githubusercontent.com/assets/20512530/25561982/2b8eed8c-2dab-11e7-8b0b-4b80aa173d19.png)

**Comment by jschr** [comment]
I get the same error on my Windows 10 machine. Looks like we're running into this electron issue: https://github.com/electron/electron/issues/9323

I added `"extract-zip": "=1.6.0"` to `package.json` to `devDependencies` [as one of the comments suggested](https://github.com/electron/electron/issues/9323#issuecomment-298205377) and that fixed it.

**Comment by Tanjh1996** [comment]
@jschr  Thanks,i have solve this,but when package and run myapp.exe it has error that 
![error2](https://cloud.githubusercontent.com/assets/20512530/25573267/5b6b7d92-2e76-11e7-804b-817ac44d5449.png)

**Comment by jschr** [comment]
hey @Tanjh1996 did you find a fix for the new error? can you share what it was?
