### ISSUE TITLE
Rendering issues after upgrading to react-router v4 & react-router-redux@next

### ISSUE THREAD

**Issue by maotora** [jschr/electron-react-redux-boilerplate#29]
Hello,

Thanks for this awesome boilerplate!

It works all fine, but I needed to upgrade to `react-router@4.1.2` & `react-router-redux@next` it ... works except, when I navigate inside a `<Route>` component (On the app side) then trigger a change on my code (Say, update some header text) Nothing gets rendered.

It's not like the BrowserSync doen't pick up the changes because the whole HTML tree gets wipedout and it's like `<html><body></body></html>`. No `<script>`s, no `<div id="app"></div>`.

[Here](https://github.com/maotora/mijengo/tree/breaking-changes/app) is my project app folder with the branch I made those changes. Please take a look at (store.js, routes.js, app.js) as those are the folders I made changes to reflect my direction.

## Update.

I think this is a problem with `react-router` not really sure, cause here.
``` jsx
export default () => {
    return (
        <Router>
            <App>
                <Switch>
                    <Route path="/login" component={Login} />
                    <Route path="/loggedin" component={LoggedIn} />
                    <Route path="/" component={MainPage} />
                </Switch>
            </App>
        </Router>
    )
}

```
That is my `<Routes />` component that I'm rendering on the main `app.js` file. 

When I edit whatever component and my app (clinet / UI side) is on route `/` aka `MainPage` I get easy reload and everything works!

However if (on the client UI side) I navigate to say, `LoggedIn` page and update something on code that mentioned issue (nothing renders) gets triggered.

Thanks.

**Comment by jschr** [comment]
I'm not sure what's causing the issue here but it looks like using hash history is the recommended way to use react-router with electron: https://stackoverflow.com/a/37080891/1249098

I cloned your project and replaced `BrowserRouter` with `HashRouter` and it seems to have resolved the issue.

**Comment by pronebird** [comment]
I just pushed #30 which implements all of the above with memory history and no issues.

**Comment by jschr** [comment]
@maotora seems like we can mark this resolved. You can use hash history or following @pronebird's latest PR for an example of using react-router-redux. 

Will close this issue but let us know if you run into any problems!

**Comment by maotora** [comment]
Wow you guys are fast that my browser didn't pick up & I had to see this on my mail before that glorious evening walk!

Thank you, it really did resolve the issue!
