### ISSUE TITLE
Rendering issues after a windows build.

### ISSUE THREAD

**Issue by maotora** [jschr/electron-react-redux-boilerplate#36]
Hello,

I wrote an app and it worked okay in development mode, (everything renders fine).

But when I made an installer for windows with `npm run pack:win` after it finishes generating 

I copied the setup to windows PC and installed, the process was smooth (no errors/warnings/exceptions).

After installation program starts and the window is blank! Restarted PC & still blank.

![Blank window](https://user-images.githubusercontent.com/5174884/28980070-1ec0eb78-7955-11e7-992f-2b1e329ea3be.PNG)

I'm not sure what is wrong but [here](https://github.com/maotora/mijengo/tree/master) is the full project.

If I should add my development system is ArchLinux.

Please help, Thanks!

**Comment by jschr** [comment]
Hey @maotora,

You can debug packaging issues by allowing dev tools to open in production here: https://github.com/jschr/electron-react-redux-boilerplate/blob/master/app/main.js#L92. Comment out the surrounding if or change to `if (true) { ... }`. 

Once you do that you'll notice a missing dependency error `redux-saga`. Running `npm install redux-saga --save` and re-packaging should fix the issue.

**Comment by maotora** [comment]
Hi @jschr ,
It worked Thanks!
