### ISSUE TITLE
raspberry pi pack

### ISSUE THREAD

**Issue by ognjetina** [jschr/electron-react-redux-boilerplate#37]
Hi, is there any chance that you will create a packager for raspberry pi?
running ``` npm run develop``` starts the app easy on raspberry pi but building it is impossible.

**Comment by pronebird** [comment]
Hi, why is it impossible to build it on raspberry pi?

**Comment by ognjetina** [comment]
I am not sure... unpacked version can be manually run and it works.
But packing fails...

**Comment by pronebird** [comment]
Maybe you could provide an error output so we could at least theorize on what's going on.

**Comment by ognjetina** [comment]
I do not have mine here right now so I cannot reproduce it currently... :/

**Comment by jschr** [comment]
Going to close this for now. Feel free to reopen if you can get an error output.
