### ISSUE TITLE
npm run pack:win won't make (explicitly specified) 32 bit builds.

### ISSUE THREAD

**Issue by maotora** [jschr/electron-react-redux-boilerplate#38]
Hi,

I'm using ArchLinux and I'm making an electron build for windows platform. I'm using `npm run pack:win` and in my `electron-builder.yml`

```yml
win:
  target: nsis
  icon: build/icon.ico
  arch:
    - x64
    - ia32
```

And when the command runs I see output 

```
...
Using electron-builder.yml configuration file
Skip app dependencies rebuild because platform is different
Packaging for win32 x64 using electron 1.7.6 to dist/win-unpacked
Building NSIS installer
  Packaging NSIS installer for arch x64
```
The execution stops at "**Packaging NSIS installer for arch x64**" never goes past that, I've also (desperately) tried `- win32` and only `- ia32` in the arch field but it doesn't build for win32.

My objective is to make either a 32bit build & a 64 bit build or a 32bit build that will also run on 64 bit machines (fall back).

I need 32 bit to work since my program will run in relatively most normal computers and most of them have 32 bit windows 7.

To avoid a long block of packages here is an image of my package.json "**dependencies**".

![package-json](https://user-images.githubusercontent.com/5174884/31307406-a03b3944-ab6c-11e7-9081-eb2ce715f03f.png)

*Still looks long, but images aren't that bad*

Thanks.

**Comment by jschr** [comment]
Hey, I think you might be better off opening an issue with electron-builder: https://github.com/electron-userland/electron-builder 

I do my best to support this boilerplate and point people in the right direction if I don't know the answer. I'm not familiar with the inner workings of electron-builder and haven't really spent much time with it so you should be able to get better support there. 

I am curious what the fix or workaround is so please post back if you find one as it may be helpful for other users who come across this issue.

**Comment by maotora** [comment]
Oh sure, I'll keep you noticed.

Thanks!

**Comment by maotora** [comment]
Hello,

My question was answered and it turned out to be pretty dumb of me not to update my `devDependencies` where `electron-builder` happened to be located at.

That solved the problem!

**Comment by jschr** [comment]
Thanks for reporting back!
