### ISSUE TITLE
Browser-sync breaking change

### ISSUE THREAD

**Issue by pronebird** [jschr/electron-react-redux-boilerplate#43]
It seems that `browser-sync@2.21` was the last version shipped with `lib` folder and we do import `browser-sync/lib/connect-utils` from it. I think changing `lib` -> `dist` should do the trick.

Compare
1. https://unpkg.com/browser-sync@2.21.0/
2. https://unpkg.com/browser-sync@2.23.6/

**Comment by phoenixrip** [comment]
This was useful to me. lib vs dist caused an error on my first npm start, but changing
`import browserSyncConnectUtils from 'browser-sync/lib/connect-utils';`
to
 `import browserSyncConnectUtils from 'browser-sync/dist/connect-utils';`  
in scripts/serve.js instantly fixed the problem!

**Comment by jschr** [comment]
Awesome! @phoenixrip happy to accept the PR if you have a fix. Otherwise I'll get to this ASAP.

**Comment by vicesalles** [comment]
Hi, browserSyncConnectUtils was throwing an error so I changed the serve file back to lib and it works.
dist-> lib. Not sure if somebody else had the same problem. Cheers.

**Comment by jschr** [comment]
Looks like we may have forgotten to bump the browsersync version number in https://github.com/jschr/electron-react-redux-boilerplate/pull/44 to `^2.23.6`. 

@vicesalles If you could confirm that also fixes it that would be appreciated!

**Comment by vicesalles** [comment]
if I update the version of browsersync to 2.23.6 the original code works fine. But with the default 2.9.3 version it crashes.

**Comment by jschr** [comment]
Great, thanks for confirming. Will push a fix.
