### ISSUE TITLE
I ran into a problem that could not open electron App with this command 'npm run develop'

### ISSUE THREAD

**Issue by mengxiaof** [jschr/electron-react-redux-boilerplate#47]
![image](https://user-images.githubusercontent.com/19354837/38071522-5a3cbfd8-3354-11e8-91e0-7541dc5abcdf.png)

**Comment by pronebird** [comment]
Hi,

That seems like an electron issue.

Since you have the compiled source could you please try running the electron directly? Maybe we could get more output.

```
cd build
electron --debug --enable-logging .
```

**Comment by jschr** [comment]
@mengxiaof Any luck figuring out what the issue was?
