### ISSUE TITLE
Unable to access local Image

### ISSUE THREAD

**Issue by sanjeevmoga** [jschr/electron-react-redux-boilerplate#51]
if I write require('path to local image'); it is showing error SyntaxError: Invalid or unexpected token I don't know how can I use Url-loader and File-loader with current project as both libraries requires webpack but we are not using webpack. 
 I used a babel file loader and in .babelrc it set 

**"plugins": ["file-loader"]**

but no luck 

what I really want to achieve is that I want to select an image and send it to print using webContents 

My Code is 

`printAll = () => {

    const { remote } = require('electron');
    const { BrowserWindow, dialog, shell } = remote;
    let printWindow = new BrowserWindow({ 'auto-hide-menu-bar': true });
    printWindow.setTitle('Print');
    //alert(JSON.stringify());
    const imageToEmbed = require(this.state.selectedFiles[0].path);
    alert(imageToEmbed);
    var my_content = "<img src ={imageToEmbed} />";
    var content_template = 'data:text/html;charset=utf-8,<html><head></head><body>' + my_content + '</body></html>'
    console.log(content_template)
    printWindow.loadURL(content_template);
    printWindow.show()
    printWindow.webContents.on('did-finish-load', function () {
      if (printWindow)
        printWindow.webContents.print();
    });
    

  }`

Please help me,Your template worked with perfection but at last I am not able to do this functionality ,Thanks

**Comment by pronebird** [comment]
Hi,

That seems like a question that belongs on StackOverflow.
