### ISSUE TITLE
Update babel config

### ISSUE THREAD

**Issue by pronebird** [jschr/electron-react-redux-boilerplate#55]
Hi,

It's been a while since we touched the babel configuration and quite a few things changed which I'd like to address at some point:

1. `preset-env` is now preferred over using specific ES presets, for instance:

```
{
      "presets": [
        ["env", {
          "targets": { "electron": "2.0" },
          "useBuiltIns": true
        }], "react"
      ],
      "plugins": [
        "transform-class-properties",
        "transform-object-rest-spread" // needed for babel 6 only, remove after upgrading to babel 7
      ]
}
```

This results in a way better JS output, since Node 8.9 and onwards support `async+await`, spreads, destructuring and many other things that we still polyfill.

2. `.eslintrc` needs to have correct `env` set and since eslint configs can cascade, it's possible to set the `env` for tests and for app code separately, i.e:

- `<root>/test/.eslintrc`:

```
{
  "env": {
    "mocha": true
  }
}
```

- `<root>/.eslintrc`:

```
{
   // what we already have there...

  "env": {
    "es6": true,
    "node": true,
    "browser": true
  }
}
```

3. Specify the target version of React used in the project using `pragma` option. This helps ESLint to turn on the correct deprecation notices when analyzing the code. Without this option it's possible to receive deprecation notices that address some changes, for instance, in React 16.3 while using React 16.2.

```
{
  // what we already have..

  "settings": {
    "react": {
      "pragma": "React",
      "version": "16.2"
    }
  }
}
```

**Comment by jschr** [comment]
Awesome! Thanks for putting this together

**Comment by jschr** [comment]
@pronebird I beleive https://github.com/jschr/electron-react-redux-boilerplate/pull/60 resolves this one?

**Comment by pronebird** [comment]
@jschr yep
