### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by pronebird** [jschr/electron-react-redux-boilerplate#56]
[Prettier](https://prettier.io) while being an opinionated code formatter, still plays the important role in code QA and saves developers from wasting time beautifying their code and arguing about code style.

So let's add it sometime soon, these are scripts we use at Mullvad:

```json
"format": "prettier --write 'app/**/*.js' 'test/**/*.js'",
"check-format": "prettier --list-different 'app/**/*.js' 'test/**/*.js'",
```

`npm run check-format` is used in Travis script to verify that the code was formatted, it will simply fail tests if the code is not formatted which should normally prevent the code from being merged to master until fixed by developer.

**Comment by jschr** [comment]
+1! I may also suggest adding the pre-commit hook: https://prettier.io/docs/en/precommit.html

**Comment by pronebird** [comment]
Not sure how that works when staging hunks vs. entire files. But why not?

**Comment by jschr** [comment]
I believe that is a current limitation. It will format the entire file when staging a chunk: https://github.com/okonet/lint-staged/issues/62
