### ISSUE TITLE
Update electron

### ISSUE THREAD

**Issue by jschr** [jschr/electron-react-redux-boilerplate#57]
Electron 2+ contains some security fixes. I took a stab a updating but ran into a bunch of warnings / errors trying to get browser sync working with a [content security policy](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#6-define-a-content-security-policy).

I gave up trying to fix the warnings for dev–[progress here](https://github.com/jschr/electron-react-redux-boilerplate/compare/update-electron). 

I'll be away for a couple weeks so I can pick this up after.

**Comment by pronebird** [comment]
Awesome! 🎉 I'd say we can live with insecure content warnings coming from `browser-sync`, since it's development only issue and shouldn't affect production.

**Comment by jschr** [comment]
Yeah. The tricky part was that complying with the new security fixes breaks browser-sync. Got stuck trying to figure out how to only enable the content security policy in production. I'm sure there's a way to do it though and a week off should help :-)

**Comment by pronebird** [comment]
Yeah, maybe we can whitelist browser-sync's URL when starting Electron from `serve.js`. Need to investigate this.

**Comment by pronebird** [comment]
FYI: since you're working on this PR, you can use `mainWindow.loadFile('build/index.html');` instead of `mainWindow.loadURL(...)`. That's something new in the Electron 2.0.
