### ISSUE TITLE
App initialization failed

### ISSUE THREAD

**Issue by jiangzhichao** [jschr/electron-react-redux-boilerplate#64]
npm version
{ 'electron-react-redux-boilerplate': '0.0.0',
  npm: '6.4.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
MacBook-Pro:electron-react-redux-boilerplate jiang$ npm run develop

> electron-react-redux-boilerplate@0.0.0 develop /Users/jiang/Desktop/project/electron-react-redux-boilerplate
> npm run private:compile -- --source-maps true && run-p -r private:watch private:serve

> electron-react-redux-boilerplate@0.0.0 private:compile /Users/jiang/Desktop/project/electron-react-redux-boilerplate
> babel app/ --copy-files --out-dir build "--source-maps" "true"

app/main/index.js -> build/main/index.js
app/renderer/actions/user.js -> build/renderer/actions/user.js
app/renderer/app.js -> build/renderer/app.js
app/renderer/components/LoggedIn.js -> build/renderer/components/LoggedIn.js
app/renderer/components/Login.js -> build/renderer/components/Login.js
app/renderer/containers/LoggedInPage.js -> build/renderer/containers/LoggedInPage.js
app/renderer/containers/LoginPage.js -> build/renderer/containers/LoginPage.js
app/renderer/reducers/user.js -> build/renderer/reducers/user.js
app/renderer/routes.js -> build/renderer/routes.js
app/renderer/store.js -> build/renderer/store.js

> electron-react-redux-boilerplate@0.0.0 private:watch /Users/jiang/Desktop/project/electron-react-redux-boilerplate
> npm run private:compile -- --source-maps true --watch --skip-initial-build

> electron-react-redux-boilerplate@0.0.0 private:serve /Users/jiang/Desktop/project/electron-react-redux-boilerplate
> babel-node scripts/serve.js

> electron-react-redux-boilerplate@0.0.0 private:compile /Users/jiang/Desktop/project/electron-react-redux-boilerplate
> babel app/ --copy-files --out-dir build "--source-maps" "true" "--watch" "--skip-initial-build"

[4110:0914/115044.670872:WARNING:backend_impl.cc(1789)] Destroying invalid entry.

**Comment by pronebird** [comment]
Hi,

What terminal do you use?

**Comment by jiangzhichao** [comment]
Hello , the installExtensions function is too slow, just annotate it

**Comment by pronebird** [comment]
🤔 I believe that the OP is using `tmux` which causes Electron to crash. Using any other shell should work just fine.

Related:
https://github.com/electron/electron/issues/10179
