### ISSUE TITLE
Console warnings in terminal

### ISSUE THREAD

**Issue by momentiris** [jschr/electron-react-redux-boilerplate#66]
Hello, and thanks for your work on this! I just started using this boilerplate and I get some console warnings in the terminal, the same ones I see in electron in the devtools console.

` "%cElectron Security Warning (Insecure Resources)", source: /Users/andreaslundqvist/Desktop/electron-react-redux-boilerplate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js (128)
[24570:1023/194308.792271:INFO:CONSOLE(188)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: /Users/andreaslundqvist/Desktop/electron-react-redux-boilerplate/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js (188)
`

I was wondering if anyone here might know how to disable these warnings from showing up in the terminal console, if possible.

Thanks.

**Comment by jschr** [comment]
Hey, the warnings came from updating to electron 2. More details are in this PR: https://github.com/jschr/electron-react-redux-boilerplate/pull/63 

The warnings appear because of browser sync client (in development). Unfortunately I'm not aware of a way disable them. I'd love to be able to though.

**Comment by jschr** [comment]
Will leave this open for visibility and in case anyone wants to tackle this.

**Comment by momentiris** [comment]
Alright. Thanks for the input!

**Comment by Anglay** [comment]
how to use less

**Comment by pronebird** [comment]
I am gonna have to add some sort of task runner to pre-process HTML to whitelist the URLs that Electron is allowed to load to fix this issue.
