### ISSUE TITLE
How to use this code on browser?

### ISSUE THREAD

**Issue by skaka30** [jschr/electron-react-redux-boilerplate#76]
Hi, this is not issue. I little bit confuse or is it possible can we deploy or can we use this code as website. For example in electron-react-redux-boilerplate  give target a specific platform like

`npm run pack:mac
npm run pack:win
npm run pack:linux`

similarly can we use `npm run build` for website? I tried to find out but not found proper solution. Please suggest me how to do this if it possible?

**Comment by pronebird** [comment]
Hi,

In theory your renderer process should use Electron IPC to talk to the main process. So you'd have to mock the IPC calls and provide other means to achieve the same on the web, given that you'd like to preserve the renderer's code. This is a boilerplate so you're welcome to clone it and shape it for your needs. We've only strictly support Electron at this time.

Cheers,
Andrej
