### ISSUE TITLE
Deploy as a Menu Bar App

### ISSUE THREAD

**Issue by athenawisdoms** [jschr/electron-react-redux-boilerplate#78]
Hello there!

How can we deploy a vanilla `electron-react-redux-boilerplate` app as a menu bar app, especially using the [`menubar` package](https://github.com/maxogden/menubar)?

For example, based on [this example](https://github.com/maxogden/menubar/tree/master/examples/hello-world), we can easily create a `menubar` app by having just `main.js` to contain

```
const { menubar } = require('menubar');

const mb = menubar();

mb.on('ready', () => {
  console.log('Menubar app is ready.');
});
```

Where should such initialization code for `menubar` be placed in the `electron-react-redux-boilerplate` code? If this is not the right approach, what is the correct way to integrate `menubar`?

**My attempt:**

![image](https://user-images.githubusercontent.com/6615285/62171067-ba153c00-b2fb-11e9-8274-82fe4796bb89.png)

I modified `init.js` to include some code using the `menubar` package, as shown below. However, the original boilerplate app still appears as per normal. Furthermore, there is now an icon in the tray, but clicking on it shows an empty white menubar screen.

```
require('./build/main');

const { menubar } = require('menubar');

const mb = menubar();

mb.on('ready', () => {
  console.log('Menubar app is ready.');
});
```

Thank you very much!

**Comment by pronebird** [comment]
Hi,

Sounds like [app/main/index.js](https://github.com/jschr/electron-react-redux-boilerplate/blob/master/app/main/index.js) is the right place to do the menubar configuration.

For more info you should perhaps ask on Stockoverflow or at the menubar's repository.

Cheers,
Andrej
