### ISSUE TITLE
Run Develop never starts

### ISSUE THREAD

**Issue by ImBeCiliC** [jschr/electron-react-redux-boilerplate#84]
Somehow after following the starting guide the gulp develop is stuck on the startin 'watch-main-scripts', 'watch-renderer-scripts' and 'watch-html'.

Some bug? or did i miss something from the setup

**Comment by pronebird** [comment]
It's not stuck, it's watching scripts. Electron should launch prior to that and you should see the browser window appear. What OS do you run it on?

**Comment by roscoevanderboom** [comment]
I also have the same problem. Running in Windows10. Running on Linux works perfectly.

**Comment by pronebird** [comment]
Alright, can you guys do the following:

1. Run `npx gulp build`
1. Run `npx electron .`

See how far it gets and post your findings.

**Comment by roscoevanderboom** [comment]
`npx build` completed but hangs on ` npx electron .` 


![Capture](https://user-images.githubusercontent.com/39595310/66013971-ffedac80-e4c4-11e9-84eb-4488e82e322c.PNG)

**Comment by pronebird** [comment]
It's possible that this issue is related to https://github.com/electron/electron/issues/19468? Nothing this boilerplate can fix if Electron hangs.

**Comment by roscoevanderboom** [comment]
ah...Thanks. I think that might be it. My windows is running in Dark Mode.

**Comment by pronebird** [comment]
I'll leave this issue open for now, we'll update the Electron as soon as the patch is out.

**Comment by ImBeCiliC** [comment]
Thanks for pointing it towards the window 10 issue. Digged around with my colleagues for a few hours yesterday. Checked different versions of Node and watched through the gulp setups but it was just not running on my device using the dark mode, but we didn't came to that conclusion. 

So **BIG THANKS** for pointing towards this issue and your support.

I also realized that the my conclusion about the watchers beeing stuck is totally false after posting so I learned my lesson to dig deeper before posting a git issue 😄 

Happy coding and awesome boilerplate!

**Comment by sbolel-doit** [comment]
I can confirm that I'm also seeing the same issue on Win10 running dark mode.

**Comment by roscoevanderboom** [comment]
Problem has been fixed with the release of Electron v8.1.1.

Runs successfully on Win10 in Dark Mode

**Comment by sbolel-doit** [comment]
Great, thank you for the update @roscoevanderboom! I will upgrade my electron today.

**Comment by jschr** [comment]
Thanks all for looking into it.  This boilerplate was updated to Electron 8.2.2 in https://github.com/jschr/electron-react-redux-boilerplate/pull/94 so this should be fixed now.
