### ISSUE TITLE
Error: 'require is not defined' when nodeIntergration : false

### ISSUE THREAD

**Issue by romanpod** [jschr/electron-react-redux-boilerplate#85]
Hi all,
When setting `nodeIntergration : false`, the app won't run.
I'm guessing that's because of how gulp transpiles the jsx:

```
var _react = _interopRequireDefault(require("react"));
var _reactDom = _interopRequireDefault(require("react-dom"));
var _reactRedux = require("react-redux");
...
```
And 'requiring' is not supported in the renderer without node integration.
I'd like to follow the electron recommendation and stick to the default setting.
Please advise.
Thanks!

**Comment by pronebird** [comment]
This is expected. Browsers do not support `require`, so you can't use it without node integration. You have to rewrite the renderer for the general web.

**Comment by romanpod** [comment]
Well, I haven't actually added any code of my own yet, I've just cloned your project, changed the setting and tried to fire it up.

**Comment by pronebird** [comment]
@romanpod yep, that won't work and I guess using Electron without `nodeIntegration` would be the entirely different approach to developing the app. 

You'd have to include all of the dependencies via `SCRIPT` tag in HTML and then smuggle the Electron IPC via the preload script.
