### ISSUE TITLE
Adoptation of Readme.md

### ISSUE THREAD

**Issue by SteffenBrinckmann** [jschr/electron-react-redux-boilerplate#89]
Dear Jschr,

Great boilerplate, there are two minor issues:
- the github link could be adopted: "https://github.com/jschr/electron-react-redux-boilerplate.git" instead of "git@github.com:jschr/electron-react-redux-boilerplate.git" which was for your account
- since one cannot build dmg from linux (?and windows?), it would be good to allow two build rules in electron-builder.yml: for me the following works fine:
mac:
  target: tar.gz
  category: public.app-category.tools

Thanks,
Steffen

**Comment by jschr** [comment]
You can build for mac, linux and windows with `npm run pack:linux`: https://github.com/jschr/electron-react-redux-boilerplate
