### ISSUE TITLE
I can't import bootstrap

### ISSUE THREAD

**Issue by fabioalxk** [jschr/electron-react-redux-boilerplate#95]
when I try to do
import "bootstrap/dist/css/" in index, it doesn't allow me to insert bootstrap there. Why?

**Comment by roscoevanderboom** [comment]
@fabioalxk Take a look at this thread. [https://github.com/jschr/electron-react-redux-boilerplate/issues/80](url)

**Comment by roscoevanderboom** [comment]
Check out https://github.com/jschr/electron-react-redux-boilerplate/issues/80

**Comment by roscoevanderboom** [comment]
You need to make changes in: 

tasks/assets.js
tasks/watch.js
gulpfile.js

**Comment by jschr** [comment]
Will re-open if issue persists after checking out #80.
