### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by HamiltonWang** [jschr/electron-react-redux-boilerplate#97]
31 warnings and 9 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR! cwd /Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=6 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=6 --node_abi_napi=napi' (1)

> core-js@3.6.5 postinstall /Users/hamiltonwang/Documents/Bitbucket/aiap_builder/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

**Comment by pronebird** [comment]
I think browser-sync is relying on old chokidar

```
$ npm ls fsevents
$ electron-react-redux-boilerplate@0.0.0 /Users/pronebird/dev/electron-react-redux-boilerplate
├─┬ browser-sync@2.26.7
│ └─┬ chokidar@2.0.4
│   └── UNMET OPTIONAL DEPENDENCY fsevents@1.2.4 
└─┬ electron-mocha@8.2.1
  └─┬ mocha@7.1.1
    └─┬ chokidar@3.3.0
      └── fsevents@2.1.2
```

Blocked by https://github.com/BrowserSync/browser-sync/issues/1765

**Comment by pronebird** [comment]
It's been a while. I don't think this is the case any longer. Please reopen if it still occurs.
