### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jschr** [jschr/electron-react-redux-boilerplate#99]
Hey @pronebird, the email I have for you doesn't seem to work anymore so pasting it here :-)

```
Hope you're doing well.

Just want to thank you for helping out with the electron-react-redux-boilerplate repo. I feel bad that I haven't been able to keep it up to date so your work is appreciated! You've made the repo a lot more useful for everyone :)

I think I mentioned this before but in case you are interested or this helps Mullvad, I'm open to transferring the repo to somewhere where it will get more attention.

But no worries if not, I still like helping out other users when I can and the help is always appreciated.

Thanks again!

Best,
Jordan

```

**Comment by pronebird** [comment]
@jschr it's totally fine that it's hosted here, I don't feel any need in changing the ownership unless you're about to archive this repo or it annoys a hell of you to receive emails from Github, then I'll accept it. We're all good don't worry, I don't have much time to maintain it either, just doing my best.
